apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/terraformprojecttest-359310/docker-registry/result-app:1.1
        name: result
        ports:
        - containerPort: 80
          name: result
        env:
        - name: PGHOST 
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: host
        - name: PGPORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: port
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password 
