apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/terraformprojecttest-359310/docker-registry/voting-app:1.0 
        name: vote
        ports:
        - containerPort: 80
          name: vote
